{% set name = "mesa" %}
{% set version = "3.3.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mesa-{{ version }}.tar.gz
  sha256: 53faf7a8d9746fe4e35030d156f55528a751a44ce9e6b4f5abfc1185cc3e881f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - setuptools
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - tqdm
    - scipy
    - networkx

test:
  imports:
    - mesa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/projectmesa/mesa
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  summary: Agent-based modeling (ABM) in Python
  description: |
    Mesa is an open-source Python library for agent-based modeling, ideal for simulating complex systems and exploring emergent behaviors.
  doc_url: https://mesa.readthedocs.io

extra:
  recipe-maintainers:
    - jackiekazil
    - dmasad
    - adamamer20
    - josk0
